version: 0.0
os: linux
files:
  - source: /addressbook.war
    destination: /usr/local/tomcat/webapps
permissions:
  - object: /usr/local/tomcat/webapps
    pattern: '**'
    mode: '0755' 
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
   ApplicationStart:
    - location: application-start-hook.sh
      timeout: 300
      runas: root
